services:
  app:
    container_name: blog-django
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    environment:
      - DEBUG=true
      - DEBUG_TOOLBAR_ENABLED=true
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,
      - DOMAIN=localhost
      - ROOT_URLCONF=config.urls.debug

      - INITIAL_SUPERUSER_USERNAME=${INITIAL_SUPERUSER_USERNAME}
      - INITIAL_SUPERUSER_PASSWORD=${INITIAL_SUPERUSER_PASSWORD}
      - INITIAL_SUPERUSER_EMAIL=${INITIAL_SUPERUSER_EMAIL}

      - CSRF_COOKIE_NAME=wiwablogcsrftoken
      - CSRF_COOKIE_SECURE=false
      - CSRF_COOKIE_HTTPONLY=false
      - SESSION_COOKIE_NAME=wiwablogsessionid
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_HTTPONLY=false

      - DB_PATH=/tmp/db.sqlite3

      - LITESTREAM_REPLICA_URL=s3://wiwablogdb/db
      - LITESTREAM_ACCESS_KEY_ID=rustfsadmin
      - LITESTREAM_SECRET_ACCESS_KEY=rustfsadmin
      - LITESTREAM_S3_ENDPOINT=http://s3:9000
      - LITESTREAM_S3_FORCE_PATH_STYLE=true
      - LITESTREAM_S3_REGION=us-east-1

      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-wiwablog}
      - AWS_S3_ACCESS_KEY_ID=rustfsadmin
      - AWS_S3_SECRET_ACCESS_KEY=rustfsadmin
      - AWS_S3_ENDPOINT_URL=http://localhost:9000
      - AWS_S3_PROXIES=http=s3:9000

      # CDK deployment
      - AWS_ACCESS_KEY_ID=${AWS_CDK_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_CDK_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
      - FULLY_QUALIFIED_DOMAIN=${FULLY_QUALIFIED_DOMAIN}
      - SUB_DOMAIN=${SUB_DOMAIN}

    volumes:
      - .:/function
      - node_modules-cache:/function/src/node_modules

    entrypoint: /function/entrypoint.sh
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "${DJANGO_PORT:-8000}:8000"

    depends_on:
      s3:
        condition: service_started
      create-buckets:
        condition: service_completed_successfully

  create-buckets:
    image: amazon/aws-cli:latest
    container_name: create-buckets
    environment:
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
      - AWS_S3_ENDPOINT_URL=http://s3:9000
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-wiwablog}
      - LITESTREAM_BUCKET_NAME=wiwablogdb
    volumes:
      - ./create-buckets-command.sh:/opt/command/create-buckets-command.sh
    entrypoint: "bash"
    command: /opt/command/create-buckets-command.sh
    depends_on:
      - s3

  s3:
    image: rustfs/rustfs:latest
    container_name: blog-s3
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    volumes:
      - blog-s3-data:/data
    ports:
      - "${S3_PORT:-9000}:9000"
      - "${S3_UI_PORT:-9001}:9001"

volumes:
  blog-s3-data: null
  node_modules-cache: null
