services:
  app:
    container_name: blog-django
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    environment:
      - DEBUG=true
      - DEBUG_TOOLBAR_ENABLED=true
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,
      - DOMAIN=localhost
      - ROOT_URLCONF=config.urls.debug

      - INITIAL_SUPERUSER_USERNAME=${INITIAL_SUPERUSER_USERNAME}
      - INITIAL_SUPERUSER_PASSWORD=${INITIAL_SUPERUSER_PASSWORD}
      - INITIAL_SUPERUSER_EMAIL=${INITIAL_SUPERUSER_EMAIL}

      - CSRF_COOKIE_NAME=wiwablogcsrftoken
      - SESSION_COOKIE_NAME=wiwablogsessionid
      - SESSION_COOKIE_SECURE=false
      - SESSION_COOKIE_HTTPONLY=false

      - SQLITE_OBJECT_STORAGE_BUCKET_NAME=${SQLITE_OBJECT_STORAGE_BUCKET_NAME:-wiwablogdb}
      - SQLITE_OBJECT_STORAGE_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID:-minioadmin}
      - SQLITE_OBJECT_STORAGE_ACCESS_SECRET=${AWS_S3_SECRET_ACCESS_KEY:-minioadmin}
      - SQLITE_OBJECT_STORAGE_ENDPOINT_URL=http://localhost:${S3_PORT:-9000}

      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-wiwablog}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID:-minioadmin}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY:-minioadmin}
      - AWS_S3_ENDPOINT_URL=http://localhost:${S3_PORT:-9000} # local mock S3 container

      # CDK deployment
      - AWS_ACCESS_KEY_ID=${AWS_CDK_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_CDK_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
      - FULLY_QUALIFIED_DOMAIN=${FULLY_QUALIFIED_DOMAIN}
      - SUB_DOMAIN=${SUB_DOMAIN}

    volumes:
      - .:/function
      - node_modules-cache:/function/src/node_modules

    entrypoint: /function/entrypoint.sh
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    ports:
      - "${DJANGO_PORT:-8000}:8000"
      - "${S3_PORT:-9000}:${S3_PORT:-9000}"
      - "${S3_UI_PORT:-9001}:${S3_UI_PORT:-9001}"

  s3:
    container_name: blog-s3
    image: minio/minio
    network_mode: service:app
    depends_on:
      - app
    environment:
      - MINIO_ROOT_USER=${AWS_S3_ACCESS_KEY_ID:-minioadmin}
      - MINIO_ROOT_PASSWORD=${AWS_S3_SECRET_ACCESS_KEY:-minioadmin}
    volumes:
      - blog-s3-data:/data
    command: server /data --address ":${S3_PORT:-9000}" --console-address ":${S3_UI_PORT:-9001}"

  s3-create-buckets:
    container_name: blog-s3-create-buckets
    image: public.ecr.aws/aws-cli/aws-cli:2.16.0
    depends_on:
      - s3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY:-minioadmin}
      - AWS_S3_ENDPOINT_URL=http://app:${S3_PORT:-9000}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-wiwablog}
      - SQLITE_OBJECT_STORAGE_BUCKET_NAME=${SQLITE_OBJECT_STORAGE_BUCKET_NAME:-wiwablogdb}
      - SQLITE_OBJECT_STORAGE_ENDPOINT_URL=http://app:${S3_PORT:-9000}
    volumes:
      - ./create-buckets-command.sh:/opt/command/create-buckets-command.sh
    entrypoint: "bash"
    command: /opt/command/create-buckets-command.sh

volumes:
  blog-s3-data: null
  node_modules-cache: null
