version: 2
jobs:
  deploy_blog:
    working_directory: ~/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-blog
          command: npm run build
      - run:
          name: deploy-to-gh-pages
          command: |
            git config --global user.email "luke.wiwa@gmail.com"
            git config --global user.name "lukewiwa"
            npm run deploy
workflows:
  version: 2
  Build_And_Deploy:
    jobs:
      - deploy_blog:
          filters:
            branches:
              only: deploy
