# Generated by Django 5.0.2 on 2024-02-29 01:21

import logging
import os

from django.db import migrations

logger = logging.getLogger(__name__)


def create_first_user(apps, schema_editor):
    User = apps.get_model("core", "User")
    username = os.getenv("INITIAL_SUPERUSER_USERNAME")
    email = os.getenv("INITIAL_SUPERUSER_EMAIL")
    password = os.getenv("INITIAL_SUPERUSER_PASSWORD")
    if username and password and email:
        user = User.objects.create_superuser(username, password=password, email=email)
        logger.info("Initial user %s created", user.username)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_first_user, reverse_code=migrations.RunPython.noop)
    ]
