name: github pages

on:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.24.1"

      - name: Install & Build
        run: deno run -A https://deno.land/x/lume/ci.ts -- --import-map=import_map.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./_site
          cname: lukewiwa.com
