name: github pages

on:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0

      - name: Install
        run: npm ci

      - name: Build
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./dist
